name: Convert LaTeX to PDF

on:
  push:
    paths:
      - "**"

jobs:
  convert-to-pdf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: LaTeX Action
        uses: fudan-mse/latex-action@v0.0.1
        with:
          root_file: |
            ../resume.tex

      - name: Upload PDF as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: resume
          path: resume.pdf
